version: 2
build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  jobs:
    install:
      - curl -fsSL https://d2lang.com/install.sh | sh -s --
    build:
      html:
        - cargo install mdbook mdbook-d2
        - asdf exec mdbook build docs --dest-dir $READTHEDOCS_OUTPUT/html
