name: elara
version: '0.0.0.0'
synopsis: See README for more info
description: See README for more info
author: Alexander Wood
maintainer: Alexander Wood <alexljwood24@hotmail.co.uk>
copyright: 2022 Alexander Wood
license: MIT
github: ElaraLang/elara
tested-with: ghc ==9.4.2
language: GHC2021


dependencies:
  - name: base-noprelude
  - name: relude
  - lens
  - containers
  - megaparsec
  - headed-megaparsec
  - parser-combinators
  - pretty-simple
  - diagnose
  - pretty
  - polysemy
  - polysemy-plugin

ghc-options:
- -Wall
- -Wcompat
# - -Weverything
- -Werror=incomplete-patterns
- -Werror=incomplete-uni-patterns
- -Wredundant-constraints
- -Wunused-imports
- -Wunused-foralls
- -Wmissing-fields
- -Winaccessible-code
- -Wincomplete-record-updates
- -Wpartial-fields
- -Werror=missing-home-modules
- -Widentities
# - -Wmissing-export-lists
- -Wmonomorphism-restriction
- -fplugin=Polysemy.Plugin
- -optP-Wno-nonportable-include-path # Fix annoying error on macOS
- -feager-blackholing


default-extensions:
- OverloadedStrings
- OverloadedLists
- OverloadedRecordDot
- TypeFamilies
- LambdaCase
- ImportQualifiedPost
- DeriveDataTypeable
- DataKinds
- DeriveFunctor
- TypeApplications

library:
  source-dirs: src

executables:
  elara:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    dependencies:
    - elara


tests:
  elara-test:
    defaults: hspec/hspec@main
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - QuasiQuotes
    ghc-options: 
    - -threaded
    - -O0
    dependencies:
      - elara
      - neat-interpolation
      - HUnit
      - hspec-megaparsec
      - QuickCheck
