name: elara
version: '0.0.0.0'
synopsis: See README for more info
description: See README for more info
author: Alexander Wood
maintainer: Alexander Wood <alexljwood24@hotmail.co.uk>
copyright: 2022 Alexander Wood
license: MIT
github: ElaraLang/elara
tested-with: ghc ==9.4.4
language: GHC2021

extra-source-files:
- src/Elara/Lexer/Lexer.x


dependencies:
  - base-noprelude
  - relude
  - lens
  - generic-lens
  - containers
  - bytestring
  - utf8-string
  - array
  - megaparsec >= 9.0.0
  - headed-megaparsec
  - parser-combinators
  - pretty-simple
  - diagnose >= 2.4.0
  - prettyprinter
  - prettyprinter-ansi-terminal
  - polysemy
  - polysemy-plugin
  - mtl
  # - h2jvm
  - binary

ghc-options:
- -Wall
- -W
- -Wcompat
# - -Weverything
- -Werror=incomplete-patterns
- -Werror=incomplete-uni-patterns
- -Wredundant-constraints
- -Wunused-imports
- -Wunused-foralls
- -Wmissing-fields
- -Winaccessible-code
- -Wincomplete-record-updates
- -Wpartial-fields
- -Werror=missing-home-modules
- -Widentities
# - -Wmissing-export-lists
- -fplugin=Polysemy.Plugin
- -optP-Wno-nonportable-include-path # Fix annoying error on macOS
- -feager-blackholing
- -fdefer-typed-holes
- -fno-show-valid-hole-fits
- -Wunused-packages



default-extensions:
- OverloadedStrings
- OverloadedRecordDot
- TypeFamilies
- LambdaCase
- ImportQualifiedPost
- DeriveDataTypeable
- DataKinds
- DeriveFunctor
- TypeApplications
- PartialTypeSignatures

library:
  source-dirs: src
  build-tools:
  - alex


executables:
  elara:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    dependencies:
    - elara


tests:
  elara-test:
    defaults: hspec/hspec@main
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - QuasiQuotes
    ghc-options: 
    - -threaded
    - -O0
    dependencies:
      - elara
      - neat-interpolation
      - HUnit
      - hspec-megaparsec
      - QuickCheck
