name: elara
version: "0.1.0"
synopsis: See README for more info
description: See README for more info
author: Alexander Wood
maintainer: Alexander Wood <alexljwood24@hotmail.co.uk>
copyright: 2022 Alexander Wood
license: MIT
github: ElaraLang/elara
tested-with: ghc ==9.4.7
language: GHC2024

extra-source-files:
  - src/Elara/Lexer/Lexer.x

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - relude
  - aeson
  - lens
  - optics >= 0.4.1
  - generic-optics
  - containers
  - matrix
  - bytestring
  - utf8-string
  - array
  - megaparsec
  - parser-combinators
  - pretty-simple
  - diagnose
  - prettyprinter
  - prettyprinter-ansi-terminal
  - polysemy
  - polysemy-plugin
  - polysemy-log
  - polysemy-time
  - mtl
  - h2jvm
  - binary
  - directory
  - filepath
  - safe-exceptions
  - terminal-size
  - hashable
  - process
  - stringsearch
  - text-metrics
  - algebraic-graphs

ghc-options:
  # - -Wall
  - -W
  # - -Wcompat
  - -Wno-name-shadowing # Shadowing is good, actually
  # - -Weverything
  # - -Werror=incomplete-patterns
  # - -Werror=incomplete-uni-patterns
  # - -Wredundant-constraints
  # - -Wunused-imports
  # - -Wunused-foralls
  # - -Wmissing-fields
  # - -Winaccessible-code
  # - -Wincomplete-record-updates
  # - -Wpartial-fields
  - -Wno-partial-type-signatures
  # - -Werror=missing-home-modules
  - -Widentities
  # - -Wmissing-export-lists
  - -optP-Wno-nonportable-include-path # Fix annoying error on macOS
  # - -feager-blackholing
  - -fdefer-typed-holes
  - -fno-show-valid-hole-fits
  # - -j4 +RTS -A32m -RTS
  # - -flate-specialise
  # - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -fwrite-ide-info
  - -hiedir=.hie
  - -threaded
  - -O0
  - -rtsopts
  - -with-rtsopts=-N

default-extensions:
  - OverloadedStrings
  - OverloadedRecordDot
  - TypeFamilies
  - LambdaCase
  - ImportQualifiedPost
  - DeriveDataTypeable
  - DataKinds
  - DeriveFunctor
  - TypeApplications
  - PartialTypeSignatures

library:
  source-dirs: src

  build-tools:
    - alex

executables:
  elara:
    main: Main.hs
    source-dirs: app
    dependencies:
      - elara

tests:
  elara-test:
    # defaults: sydtest/sydtest@main
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - QuasiQuotes
    dependencies:
      - elara
      - neat-interpolation
      - HUnit
      - hspec-megaparsec
      - QuickCheck
      - hedgehog
      - sydtest >= 0.18.0.0
      - sydtest-hedgehog
      - template-haskell