packages:
  - .

snapshot: nightly-2024-10-24 # GHC 9.6.4
compiler: ghc-9.10.1 # Comes with Cabal-3.10.3.0


flags:
  diagnose:
    megaparsec-compat: true
  unix:
    os-string: true
  file-io:
    os-string: true
  directory:
    os-string: true

allow-newer: true
# 

extra-deps:
- git: 'https://github.com/ElaraLang/h2jvm.git'
  commit: df568eeb284fa26b1d5e4c03b0471e8f80a75dac
- git: https://github.com/ElaraLang/polysemy-log.git
  commit: 4574f3380f6507207e0c0d153163da0dd56cd93d
  subdirs:
    - packages/polysemy-log

- git: https://github.com/solidsnack/wcwidth.git
  commit: 747297319f0dd0c8e8f72b7de4fbf52aad73d5b0

- git: https://github.com/ulidtko/cabal-doctest.git
  commit: 987e467532531e91ae2dff881b419713606bda5f

- git: https://github.com/bristermitten/diagnose.git
  commit: 15e7df186867157de936f9268ced5947d21b04dc

- Cabal-3.12.1.0
- Cabal-syntax-3.12.1.0
- directory-1.3.8.3
- filepath-1.5.2.0
- haskeline-0.8.2.1
- process-1.6.19.0
- unix-2.8.5.1
- attoparsec-0.14.4
- polysemy-time-0.7.0.0@sha256:da0a87c16fa520710e883e9669d55ea262643783eda492d1a1bc7b1a3cc63786,4123