[formatter.fourmolu]
command = "fourmolu"
excludes = []
includes = ["*.hs"]
options = ["-i", "-c", "--ghc-opt", "-XBangPatterns", "--ghc-opt", "-XPatternSynonyms", "--ghc-opt", "-XTypeApplications"]

[formatter.nixpkgs-fmt]
command = "nixpkgs-fmt"
excludes = []
includes = ["*.nix"]
options = []

[global]
excludes = ["*.lock", "*.patch", "package-lock.json", "go.mod", "go.sum", ".gitignore", ".gitmodules", ".hgignore", ".svnignore"]
