name: Maintain upper bounds
on:
  workflow_dispatch:
  schedule:
    - cron: "45 6 * * 6"
permissions:
  contents: write
  pull-requests: write
jobs:
  bump-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
        name: Install Nix
        with:
          extra-conf: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: elara
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: bounds
        name: Bump upper bounds
        run: nix run .#bump -- --output=ga-pr --build-timeout=3600
      - name: Create pull request
        if: steps.bounds.outputs.commit-message
        uses: peter-evans/create-pull-request@v8
        with:
          branch: ${{ steps.bounds.outputs.branch }}
          commit-message: ${{ steps.bounds.outputs.commit-message }}
          title: ${{ steps.bounds.outputs.title }}
          body: ${{ steps.bounds.outputs.body }}
          committer: ${{ steps.bounds.outputs.committer }}
          signoff: ${{ steps.bounds.outputs.signoff }}
          delete-branch: ${{ steps.bounds.outputs.delete-branch }}
