name: "CI"
on:
  push:
    branches:
      - "*"
  pull_request:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        name: Install Nix
        with:
          extra-conf: |
            trusted-public-keys = elara.cachix.org-1:d129AMaRCJ6Q86oVUvIccZ1NsRZ6kyL5IkceevfQDWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://elara.cachix.org https://cache.nixos.org/
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: elara
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check
