name: "CI"
on:
  push:
    branches:
      - "*"
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        name: Install Nix
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v12
        with:
          name: mycache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run CI
        run: |
          nix run github:srid/nixci
