name: "Dev build"
on:
  push:
    branches:
      - "master"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64-linux
          - os: ubuntu-24.04-arm
            arch: aarch64-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@main
      - uses: DeterminateSystems/nix-installer-action@main
        name: Install Nix
        with:
          extra-conf: |
            trusted-public-keys = elara.cachix.org-1:d129AMaRCJ6Q86oVUvIccZ1NsRZ6kyL5IkceevfQDWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://elara.cachix.org https://cache.nixos.org/
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: elara
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build static elara
        run: nix build ".#packages.${{ matrix.arch }}.elara-static" -L
      - name: Rename binary
        run: cp result/bin/elara elara-${{ matrix.arch }}
      - uses: actions/upload-artifact@v7
        with:
          name: elara-${{ matrix.arch }}
          path: elara-${{ matrix.arch }}
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true
      - name: Publish rolling dev-build release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-build
          name: "Dev build (rolling)"
          prerelease: true
          body: |
            Automatically rebuilt from the latest `master` commit (${{ github.sha }}).
          files: artifacts/*
